const locations = [
  'Remote',
  'Arad',
  'Bucuresti',
  'Botosani',
  'Brasov',
  'Buzau',
  'Baia Mare',
  'Cluj-Napoca',
  'Constanta',
  'Craiova',
  'Deva',
  'Hunedoara',
  'Galati',
  'Iasi',
  'Oradea',
  'Pitesti',
  'Ploiesti',
  'Ramnicu-Valcea',
  'Resita',
  'Sibiu',
  'Suceava',
  'Targu-Mures',
  'Timisoara',
];
const domains = [
  'Achiziții',
  'Administrativ',
  'Agricultura',
  'Alimentatie / HoReCa',
  'Arhitectura',
  'Asigurari',
  'Audit / Consuntanta',
  'Auto / Echipament',
  'Automatizari',
  'Banci',
  'Cercetare',
  'Chimie',
  'Confecții',
  'Constructii',
  'Contabilitate',
  'Farmacie',
  'Grafica / WebDesign',
  'Imobiliare',
  'Import-Export',
  'Inginerie',
  'IT&C',
  'Juridic',
  'Jurnalism',
  'Management',
  'Marketing',
  'Medicină',
  'Merchadising / Promoteri',
  'Pază',
  'Petrol / Gaze',
  'Prelucrarea lemnului / PVC',
  'Project Management',
  'Protecția muncii',
  'Publicitate',
  'Relații clienți',
  'Resurse umane',
  'Saloane',
  'Service / Reparații',
  'Telecomunicații',
  'Tipografii / Edituri',
  'Traduceri',
  'Transport / Distribuție',
  'Turism',
  'Vânzări',
];
const studies = [
  'Studii gimnaziale',
  'Studii profesioanele(scoala de meserii)',
  'Studii liceale',
  'Studii universitare',
  'Studii postuniversitare',
];
export { locations, domains, studies };
