version: "3.7"

services:
  client:
    image: client
    container_name: client-container
    ports:
      - 3000:3000
  auth-server:
    image: auth-server
    container_name: auth-server-container
    ports:
      - 4001:4001
  post-server:
    image: post-server
    container_name: post-server-container
    ports:
      - 4002:4002
  user-server:
    image: user-server
    container_name: user-server-container
    ports:
      - 4003:4003
  comment-server:
    image: comment-server
    container_name: comment-server-container
    ports:
      - 4004:4004
